#!/usr/bin/env python3
"""
export_fps_for_voxel51.py -- exhaustive (NOT sampled) export of every false positive at a given
confidence floor, for a single background-level model, as a plain CSV.

Built for Danelle's Voxel51 workflow: she will cluster/relabel these against the normal
annotation standard and feed corrections back into the master test-set database. Unlike
crop_false_positives.py (which samples ~200 per level and crops images for human eyeballing),
this script does NO sampling, NO per-image capping, and NO image cropping -- every single false
positive at the given confidence floor is included, with the file name and box coordinates
exactly as stored in the source detections JSON, unmodified.

Uses the SAME false-positive definition already established and verified against the paper's own
Table 1 in crop_false_positives.py: one-to-one, confidence-ordered greedy matching (each
ground-truth box claimable by at most one prediction), false positive = no unclaimed GT within
--iou-thresh.

Output columns match the manifest format used elsewhere in this project (crop_filename,
source_image, x1, y1, x2, y2, confidence, bg_level, category, Notes) for consistency with the
hand-categorization manifests. IMPORTANT: crop_filename here is a PREDICTED name following the
same convention crop_false_positives.py uses (crop_NNNN_stem_confXX.jpg) -- no actual crop image
is generated by this script, and the numbering is a simple sequential count over the full
exhaustive list, so it will NOT match any crop_false_positives.py sampled-run numbering for the
same real-world box. category and Notes are intentionally blank, ready for Danelle's own labeling
pass in Voxel51.

Run:
  python export_fps_for_voxel51.py --det-file model_compare/native_v1_gtfixed/detections_bg20.json \
    --conf 0.3 --label 20bg --out fp_export_20bg_conf03.csv
"""
import os
import csv
import json
import argparse


def iou(boxA, boxB):
    xA1, yA1, xA2, yA2 = boxA
    xB1, yB1, xB2, yB2 = boxB
    ix1, iy1 = max(xA1, xB1), max(yA1, yB1)
    ix2, iy2 = min(xA2, xB2), min(yA2, yB2)
    iw, ih = max(0, ix2 - ix1), max(0, iy2 - iy1)
    inter = iw * ih
    if inter <= 0:
        return 0.0
    areaA = (xA2 - xA1) * (yA2 - yA1)
    areaB = (xB2 - xB1) * (yB2 - yB1)
    union = areaA + areaB - inter
    return inter / union if union > 0 else 0.0


def match_image(gt_boxes, preds, iou_thresh):
    """Same one-to-one, confidence-ordered matching as before, but returns BOTH the false
    positives AND the true positives (with which GT each claimed) -- needed to compute the
    NMS-duplicate overlap signal below."""
    order = sorted(range(len(preds)), key=lambda i: -preds[i][1])
    claimed_gt = set()
    fps, tps = [], []
    for i in order:
        pxy, pconf = preds[i]
        best_iou, best_g = 0.0, -1
        for g, gbox in enumerate(gt_boxes):
            if g in claimed_gt:
                continue
            v = iou(pxy, gbox)
            if v > best_iou:
                best_iou, best_g = v, g
        if best_iou >= iou_thresh:
            claimed_gt.add(best_g)
            tps.append((pxy, pconf))
        else:
            fps.append((pxy, pconf))
    return fps, tps


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--det-file', required=True, help='a detections_bgNN.json file (GT-corrected)')
    ap.add_argument('--conf', type=float, required=True, help='confidence floor, e.g. 0.3')
    ap.add_argument('--iou-thresh', type=float, default=0.1,
                     help='matching threshold, matches Table 1 convention (0.1)')
    ap.add_argument('--label', required=True, help='short tag for this background level, e.g. "20bg" -- populates bg_level column')
    ap.add_argument('--out', required=True, help='output CSV path')
    args = ap.parse_args()

    with open(args.det_file) as f:
        d = json.load(f)
    records = d['records']

    total_preds = 0
    all_fps = []  # (image, x1, y1, x2, y2, confidence, max_iou_vs_tp, matched_tp_conf)
    for r in records:
        gt_boxes = r['gt']['xyxy']
        preds = [(xy, c) for xy, c in zip(r['pred']['xyxy'], r['pred']['confidence']) if c >= args.conf]
        total_preds += len(preds)
        fps, tps = match_image(gt_boxes, preds, args.iou_thresh)
        for (x1, y1, x2, y2), conf in fps:
            # NMS-duplicate signal: how much does this FP overlap an ALREADY-correctly-matched
            # TP on the same image? High overlap suggests this FP is a duplicate/sliver
            # fragment of an object the model already found correctly (a post-processing
            # artifact), not a genuine annotation gap or hallucination.
            best_tp_iou, best_tp_conf = 0.0, None
            for tp_xy, tp_conf in tps:
                v = iou((x1, y1, x2, y2), tp_xy)
                if v > best_tp_iou:
                    best_tp_iou, best_tp_conf = v, tp_conf
            all_fps.append((r['image'], x1, y1, x2, y2, conf, best_tp_iou, best_tp_conf))

    with open(args.out, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['crop_filename', 'source_image', 'x1', 'y1', 'x2', 'y2', 'confidence',
                          'meets_conf_0.5', 'max_iou_vs_matched_TP', 'nearby_TP_confidence',
                          'bg_level', 'category', 'Notes'])
        for i, (image_name, x1, y1, x2, y2, conf, tp_iou, tp_conf) in enumerate(all_fps):
            stem = os.path.splitext(image_name)[0]
            crop_fname = f'crop_{i+1:04d}_{stem}_conf{conf:.2f}.jpg'
            meets_05 = 'Yes' if conf >= 0.5 else 'No'
            tp_conf_str = f'{tp_conf:.3f}' if tp_conf is not None else ''
            writer.writerow([crop_fname, image_name, x1, y1, x2, y2, f'{conf:.3f}', meets_05,
                              f'{tp_iou:.3f}', tp_conf_str, args.label, '', ''])

    print(f'{total_preds} predictions at conf>={args.conf}')
    print(f'{len(all_fps)} false positives (IoU<{args.iou_thresh} vs all GT, one-to-one matching)')
    print(f'Wrote ALL {len(all_fps)} to {args.out} -- no sampling, no per-image cap')


if __name__ == '__main__':
    main()
